// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/canvas/index.vue')['default']
    CollapseTransition: typeof import('./src/components/collapse-transition/index.vue')['default']
    ConfigItem: typeof import('./src/components/config-item/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    Help: typeof import('./src/components/help/index.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    Shape: typeof import('./src/components/shape/index.vue')['default']
    Socket: typeof import('./src/components/socket/index.vue')['default']
    TemplateParser: typeof import('./src/components/template-parser/index.vue')['default']
  }
}

export { }
