// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/canvas/index.vue')['default']
    CollapseTransition: typeof import('./src/components/collapse-transition/index.vue')['default']
    ConfigItem: typeof import('./src/components/config-item/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
  }
}

export { }
